- name: run show version on remote devices
  connection: local
  timeout: 360
  junipernetworks.junos.junos_command:
    commands:
      - show version
      - show interfaces
      - show system uptime
  register: out01

- debug:
    var: out01