- name: run show version on remote devices
  connection: local
  junipernetworks.junos.junos_command:
    commands:
      - show version
      - show interfaces
      - show system uptime
  register: out01
  timeout: 60

- debug:
    var: out01