- name: save device configuration
  juniper_junos_config:
    provider: "{{ connection_settings }}"
    dest: "{{ config_filename }}"
    format: text
    retrieve: committed
- include_tasks:
  name: display path to latest backup file
    debug:
     msg: "The configuration backup is in {{ config_filename }}"

